project:
  type: book
  # change output-dir to "docs" to publish to gh pages
  output-dir: docs

book:
  title: "Jelinski Lab Protocols"
  author: "N.A. Jelinski, N.B. Pearson, and all other lab members"
  date: "16-November-2023"
  cover-image: "laboratory-protocols-badge.png"
  
  chapters:
    - index.qmd
    - part: "Protocols"
      chapters: 
      - amm-ox-copy.qmd
      - ammonium-oxalate-extraction.qmd
      - cec-extraction.qmd
      - chromatography.qmd
      - cleaning-earthworms.qmd
      - dithionite-citrate-extraction.qmd
      - dry-sieving.qmd
      - ec-soluble-salts.qmd
      - electrical-conductivity.qmd
      - hydrometer.qmd
      - laser-particle-size-analysis.qmd
      - loss-on-ignition.qmd
      - mir.qmd
      - mixing-SHMP.qmd
      - moisture-content-bulk-density.qmd
      - particle-density-pycnometers.qmd
      - pb-bioaccessibility.qmd
      - permafrost-soil-processing.qmd
      - pH.qmd
      - pipette-texture.qmd
      - pXRF.qmd
      - wet-sieving.qmd
    - part: "Laboratory Safety"
      - part: "Radiation Safety"
        chapters:
        - pXRF-user-guidelines.qmd
        - radiation-and-pXRF-safety-training.qmd
        - pXRF.qmd
#    - summary.qmd
#    - references.qmd
#  appendices:
#    - co-authorship-template.qmd
#    - data-use-and-sharing.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual


