---
title: "Earthworm Collection and Cleaning"
format: html
editor: visual
---

::: callout-note
Last edited: 06NOV2023 NP

**Collection**: Earthworms should be collected at the end of the year after the final harvest and soil samples have been collected. It is very important that they are collected **first**.

**Cleaning**: Within 24 hours, the samples all need to be cleaned and filled with 95% Ethanol. If the samples have been sitting in the lab and the liquid looks yellow, the sample should be recleaned and replaced with clean 95% Ethanol.
:::

## Collection

#### Materials

-   Sample rings (1-3)
-   Shovels: trowel and hand shovel
-   Tarp
-   50mL Falcon tubes
-   Acetate
-   70% Ethanol
-   Powder mustard
-   Gallon jugs of water +1 extra
-   Tweezers
-   Small containers
-   Marker
-   Field gloves/lab gloves
-   Acetate waste container (1L Nalgene)
-   Funnel
-   Measuring cup

#### Procedure

-   For each plot, you will need a jug of water mixed with ⅓ cup of the mustard powder. Take the small container and put some acetate in it, this will be referred to as the kill jar.
-   To start, clear the sampling area from loose debris such as leaves and sticks. Place the sample ring in the soil deep enough that liquid would not go out from its sides. Once the ring has been secured, pour about ⅓ to ½ of the mustard water in a circular motion within the ring. Record the time started with mustard. We would like to keep a consistent timeline. Once the liquid all goes down into the soil, add more. The pouring should take 2-3 rounds.
-   Collect any worms that may come up and transfer them into the kill jar. When they stop moving they can be transferred into a tube labeled for the site/plot/date and that they came up from mustard. Tweezers are helpful so your fingers don't have to touch the acetate. When in the tube, fill until it is over the worms to \~10mL of the 70% ethanol.
-   When the mustard water has been fully drained, record the time, lay down the tarp next the the ring, and start digging within the ring. Try to keep the soil layers organized like top soil further from the ring and the bottom closer to the ring. That way, the hand sorting can be brought back to its original layer at the end. Dig to 12 inches in depth. Worms that are half in the hold and half out count as in.

::: callout-tip
Scrape the sides to make sure we get the full area. Worms really like clumps and root masses.
:::

-   Hand sort the soil to pull any worms that appear. As collecting put them into the kill jar. This gets really muddy. Slowly put the soil back into the hole. Try to clean the worms in the kill jar to get as much of the soil off as you can. Place them into a tube labeled site/plot/date and hand sort. When in the tube, fill until it is over the worms to \~10mL of the 70% ethanol. Dump the waste acetate soil into the waste container. Use the extra water to do a quick rinse of the soil off of the tray/container so it's ready for the next plot.

## Cleaning

#### Materials

-   Lab gloves
-   Worm samples (50 mL Falcon tubes)
-   Fume hood
-   Paper towels
-   DI water
-   Marker
-   95% Ethanol
-   Beaker for ethanol (\~100mL)
-   Beaker for waste (2L)
-   Waste container for ethanol and funnel
-   Tweezer
-   Secondary containment tray/small tray

#### Procedure

-   Prep includes filling the smaller beaker with ethanol for easier pouring, setting up the final waste stage (container and funnel if needed), and have a wash bottle of DI water filled.
-   In the fume hood, take the tube with the worm sample that needs to be cleaned and dump the contents in the small tray. Use the DI bottle to wash the inside of the tube, sometimes soil collects in the bottom or the outside is dirty from collection. Set the tube aside temporarily. Clean the worms with a combination of light rubbing with gloves on and washing with DI water. As they get clean, place the worm back into the original container until they are all in there.
-   Fill the tube with the ethanol \~5-10mL over the worms. If any ethanol hits the side of the tube the label may smear off. Take the paper towel to dry off the tube and relabel when it's dry, which is almost instantly. Once sample is cleaned put it off to the side with the other clean samples.
-   The waste from that sample can go into the bigger beaker. Sometimes in this movement smaller worms are easier to see (especially if there is another of soil/mud in the tube). Moving the waste twice allows to ensure each worm is going back into the sample and not getting dumped. Once the beaker fills up, discard into the final waste container.

## References and Notes
