# Loss on Ignition

::: callout-note
Last edited: 08NOV2023 NP

Loss on ignition (LOI) is used to determine the organic matter (OM) percentage of a soil sample.

[Example data sheet](https://docs.google.com/spreadsheets/d/1Z6ijR4D47hjFZBMePrvnEEBT6g56EIJs/edit?usp=sharing&ouid=108934466869932900090&rtpof=true&sd=true)
:::

## Materials

-   Lab coat
-   Safety goggles
-   Oven safe gloves
-   Tongs to lift and move hot crucibles
-   Muffle furnace at 550ยบ Celsius
-   4-digit analytical balance
-   \~5 g air-dried soil of each sample
-   Measuring scoop
-   Kim wipes
-   2-3g air-dried soil sample (to use for moisture correction measurement)
-   Desiccator filled with Anhydrite
    -   Should be blue in color; if it is purple or pink, see directions below
-   Ceramic crucible (oven-dried and numbered on exterior base)

## Procedure

-   Prepare laboratory notebook with the following data columns:
    -   Sample number, crucible number, oven dry (OD) crucible (g), pre-muffle crucible+soil (g), post-muffle crucible+soil (g)
-   A few samples will be used for calculating a moisture correction. See below. Data columns:
    -   Crucible number, OD crucible (g), air dry moisture correction soil +OD crucible (g), OD moisture correction soil + OD crucible
-   Rinse the crucibles with DI water and place them in drying oven at 105 degrees Celsius overnight (or 6-8 hours).
-   Take the crucibles out of the oven and place them into the desiccator where they can cool for a couple minutes. Your cooling time (such as 5 minutes) should become a standard for all samples in your set.

::: callout-note
The 4-digit analytical balance does not like hot items, so the crucibles must cool down before weighing. Cool to the touch is fine. When hot items are placed onto the scale, the air and metals in the scale expand and the scale gets wonky. It ends up reading a negative value when the items are removed from the scale. So, I placed the crucibles from the oven into a desiccator because I felt that the oven dry crucibles gained water weight from the moisture in the air while sitting out in the lab. I wanted to keep them as dry as possible to reduce the chance that such gained moisture weight wouldn't be inaccurately counted as soil weight.
:::

-   Weigh each crucible on the 4-digit analytical balance; record the OD weight and the number of the crucible.

-   Do not tear the weight of the crucible. Gently mix the soil around in the bag so that you have a homogenous sample, and add \~5 g soil into the crucible with a small scoop.

-   Document OD crucible + soil weight (g).

-   Place the crucible and soil onto the ceramic plate that will be slid into the muffle furnace.

::: callout-note
Some folks make a map of which crucibles are on the plate, but I chose to document the number of the crucible and which sample was placed into that numbered crucible in my lab book. I did have to lift the crucible up high to see the number on the bottom when I went to weigh it. Perhaps a combination of both listing the crucible number and using a layout map would be useful for identifying the samples when they are taken out of the furnace to weigh.
:::

-   Wipe off the scoop and repeat the weighing procedure. Complete this soil measurement and weighing process for the chosen number of samples you will do.

::: callout-note
I recommend 12-18 samples at a time. More of the smaller crucibles can fit into the muffle furnace on the ceramic plate, but the small crucibles are more challenging to pick up (you should use the tongs, trying to grab it with oven mitts on is probably not possible to do). Also, 5 g of an organic sample will not fit into a small crucible. If you fill the ceramic plate that slides into the muffle furnace with too many crucibles, you risk having crucibles sliding/falling off the edge --which means a loss of your sample and its data.
:::

-   Note that the temperature of the muffle furnace has warmed to 550ยบ C. Load the ceramic plate and slide it into the muffle furnace. Close and latch the door and let the samples bake for exactly 5 hours.

-   After 5 hours, turn the furnace off and crack the door open to allow some heat to escape for 5-10 minutes.

-   Carefully remove the samples from the muffle furnace. Be careful. Either place them in the drying oven or into the desiccator to cool some before weighing them. Don't let them sit out at room temperature because they will absorb moisture from the air. If you leave them in the desiccator, be sure to crack the lid or rubber stopper to avoid a pressure inconsistency.

::: callout-note
If you don't crack the lid, the desiccator will suck in air when you open it and sample will fly everywhere.
:::

-   Taking one sample out of the desiccator at a time, weigh each sample shortly after it has cooled to the touch (5 minutes, or same amount of time afterward as before when you let the crucibles sit after being in the drying oven).

::: callout-warning
Watch out - the weight of the sample will increase the longer it is exposed to the air as the soil particles are absorbing moisture. Take the first reading you see, that is, when you feel that scale is balanced after the sample is set onto it.
:::

## Moisture Correction

#### Procedure

-   Use a 2-3g air-dried soil sample, weigh the oven-dried crucible (do not tear the weight after), then add the soil sample.
-   Place into the drying oven at 105ยบ C for 24 hours.
-   After taking the sample out of the oven, place it into the desiccator for a couple of minutes to cool.
-   Weigh it on the 4-digit analytical balance.

Mineral soil samples will hold different percentages of moisture than organic samples, so you should take a moisture correction for each category of soil sample (i.e. mostly mineral, mineral-organic combination, mostly organic), not one for every sample. Moisture corrections should be run at the same time/day as the LOI procedure. Run a moisture correction at each time you run an LOI set.

## Calculation
Capital M indicates mass.

#### Moisture Correction
$$
[M(oven\ dry\ moisture\ correction\ soil\ +\ oven\ dry\ crucible) - M(oven\ dry\ crucible)] \over [M(air\ dry\ moisture\ correction\ soil\ +\ oven\ dry\ crucible) - M(oven\ dry\ crucible)]
$$

Alternatively, if the mass of the oven dry crucibles are subtracted from the oven and air dry soil mass (isolating the soil masses), the equation is as follows.

$$
M(oven\ dry\ moisture\ correction\ soil) \over M(air\ dry\ moisture\ correction\ soil)
$$

#### Organic Matter %

$$ 
[M(air dry soil + crucible) - M(oven dry crucible) * moisture correction] - [M(oven dry soil + crucible) - M(oven dry crucible)] \over [M(air dry soil + crucible) - M(oven dry crucible) * moisture correction]
$$
**Multiply this value by 100%.**

Alternatively, if the mass of the oven dry crucibles are subtracted from the post-muffle furnace (written in equation as oven dry) and air dry soil masses (isolating the soil masses), the equation is as follows.

$$
(M(air\ dry\ soil)\ *\ moisture\ correction) - M(oven\ dry\ soil) \over (M(air\ dry\ soil)\ *\ moisture\ correction)
$$

**Multiply this value by 100%.**

## Recharging Anhydrite

Anhydrite should be blue. If it is purple/pink, place the Anhydrite into a metal pan (9x13" cake pan) and oven dry at 105 degrees Celsius until the blue color has come back indicating that the material has lost all moisture. This should take less than 24 hours.

## References and Notes
