---
title: "Pipette (Texture)"
format: html
editor: visual
---

::: callout-note
Last edited: 09NOV2023 NP

Pipette is a method used to determine silt & clay size fractions in soil samples.Your sample should be wet sieved prior to this; see the wet sieving protocol for more information.
:::

## Materials

-   Column of blank with 100ml SHMP
    -   Fill to 1 L with DI water. The room temperature will be taken from this blank. You also likely used this blank in the hydrometer run. If you have prepared a new blank -- this column should have sat in the same room as the other columns so that it has the same temperature as all the columns. The reason I mention this is because the building DI water is warmer than room temp; therefore, it should be allowed to acclimate to room temperature; overnight is best.
-   Sedimentation columns
    -   For post hydrometer for testing. For each run, the maximum is probably 8 columns (including the blank). I'd recommend 4-5 columns per run for beginners, working up to 8 columns per run for advanced pipetters.
-   Extra column
    -   Filled with DI for rinse. This can be filled higher than the 1L mark. This is not for measurements, just for rinsing the pipette between samples.
-   400mL beaker
    -   To catch "dirty" rinse water. Set this inside the rinse column, then the pipette bar doesn't have to be moved, just the pipette swiveled to where the rinse water can drop down into the beaker.
-   Tins, Oven Dry (OD)
    -   Tins should have been in the oven overnight (4-6 hours) so that they are oven dry. I think it's best not to use tins that are dry but sitting out, room temp, because of the slight moisture they absorb.
-   Oven dry tin weight
    -   After taking the tins out of the oven, place them in the desiccator. After 2-3 minutes they are cool to the touch and can be weighed. I found that leaving all the tins in the desiccator and taking one out at a time works well. With the direrite in the desiccator, little moisture can be absorbed by the tins.
-   Column mixer/ plunger
    -   As the columns sit after the wet sieving, the sediment can start to collect and form a cake to the bottom. You will have to plunge quite strongly to get this sediment to be suspended. Firmly hold the column with one hand so it is sturdy, plunge with the other hand.
-   Timer
    -   Keep track of the time you start each sample. You will take the first pipette measurement after approximately 4 ½ mins (for the 20 micrometer particle) and then after 4 ½ hours (or after the period you choose for the 2 micrometer particle). These times are specifically written in the master book on page 62 & 63. If you choose a 4 ½ hour reading, for example, continue this same time of reading for all samples you do, even if they are taken during future runs.

## Procedure

-   Prepare laboratory notebook with the following data columns:
    -   Sample ID
    -   Temperature of Blank
    -   Time of start: minutes and seconds. I use the stopwatch on my phone and let it run, recording what time I take the plunger out -- such as 00:00 (minutes:seconds), then 07:00 (for the second test)
    -   Tin \# being used
    -   Oven Dry tin weight (tin pulled from desiccator)
    -   Wet weight (sample + tin)
    -   Dried Sample + tin oven dry weight: this sample will be placed in the desiccator for 2-3 minutes to cool and then should be weighed directly from the desiccator to minimize moisture it can absorb from the air. Note -- when you take this weight on the 4-digit balance, the weight will increase steadily due to moisture absorption -- so take the first stable weight you see.

#### Pre-Procedure Thoughts

-   Practice the procedure with the column of rinse water before starting. This gets the vacuum pressure and your technique just right. With the vacuum and hose, the pipette will require about \~12 seconds to fill.
-   This is important: Do not let the sample get up into the bulb -- a bubble that forms underneath can trap some of your sample from being released.
-   Double and triple check that the vacuum hose is disconnected before turning the knob to release your sample. You do not want your sample to escape upward into the hose if the vacuum is still on.
-   Set up your columns so that the pipette is lowered in the center of the column as opposed to the edge next to the glass. You won't want to move the sedimentation columns once you start.
-   Use weight boats to cover the samples you are not working. Best not to lets drips fall into them (contamination).
-   Set the vacuum so that the black lines are lined up with each other.

#### First Reading: 20 micrometer particle

Using the book and the temperature of the blank, you will learn what the first time of your pipette will occur. The 20-micrometer reading will always be at 10cm, but at a varying time from the end of the mixing (depending on the temperature taken from the blank). This 10 cm level needs to be set on the pipette. The measuring tool goes from zero on the bottom and upward to 10. The movable measuring bar/stopper gets set at the 10.0 line. Not all the way to the top, that is more than 10.0 cm. If this isn't clear, take a extra moment to look at the way the measuring tool is designed.

-   Ready -- plunge! All sediment needs to be suspended. Carefully, but firmly mix. Use two hands - one to hold the column and one to plunge. When the plunger is taken out of the column, this is time = 0. Wait the 4 minutes and some seconds (according to the temperature and the reading in the book p.62)
-   As you are waiting this 4 and some minutes, weigh the tin you recently removed from the oven and placed into the desiccator. Record the tin number and it's oven dry weight.
-   When time is near to pull the first sample, make sure the vacuum is turned on, the hose is disconnected, the white knob on the pipette is CLOSED. With the 10 cm setting, lower the pipette apparatus so that the end tip of the pipette just touches the surface of the liquid in the column. Lower the pipette the 10 cm preset measurement.
-   At the time your measurement is due attach the hose then open the knob. Hopefully you have practiced with clean DI water so that you have the vacuum pressure set correctly - approx. 12 seconds for the pipette to draw the sample to the line.
-   Stop by closing the knob, then pull off the hose from the vacuum nozzle. Leave the vacuum on and set to the correct pressure you've determined. You will not need to turn the vacuum off. The hose goes on and off, but the white knob is most important for your control. This starts and stops the pipette from drawing your sample.
-   With the hose off the vacuum (double check this) swivel the pipette and release the sample into your oven dry tin. Take the weight on the 4-digit scale immediately at the soonest you can, as evaporation is happening. If the sample is stable on the scale, take the first weight you feel is accurate, yet the weight will continuously be decreasing (due to the evaporation). Now that you have the weight, it's ok to leave it sitting until you have all your samples to put into the oven for your 24 hours oven dry.
-   Rinse once or twice between each sample
-   Complete the run of all your samples.
-   Tins with wet sample can be put into the oven to dry 24 hours (105 degrees C, with the plug on the oven top so it is closed).

#### Second Reading: 2.0 micrometer particle

This is very similar to the initial procedure, but this time the depth of measurement will be the variable, dependent on the time you chose and the current temperature of the blank. If you select the 4 ½ hour time, you will continue this throughout all of the sample runs you do. Your depth of reading will be found on page 63, under the 2.0-micrometer page. It will probably be 5.7cm or something similar. This is the depth from the surface of the suspension. The measurement bar is measured from the bottom to the top.

::: callout-note
The trick with this reading is that the pipette won't swivel from sample to sample because the columns are too tall. Each time the glass pipette is above a sample column, you will have to set the depth of reading. This can be a little tricky. After you have pulled the sample, you will have to raise the measuring bar and raise the pipette all of the way. Then the pipette tip is clear to swivel.
:::

-   Again, tins should be pulled from the oven and into a desiccator. They should be able to cool before they are weighed on the 4-digit scale. I like to weigh the tin just before I use it. I choose not to let them sit out as I feel they take on some weight of moisture, which then alters the measurement.
-   You will take the same volume of measurement for the second reading.
-   You can also take a sample from the blank on the second reading.

#### Post oven: oven dry weight

-   Remove samples from the drying oven and place them into a desiccator for 2-3 minutes to cool to touch.
-   Weight them individually on the 4-digit balance and record the sample's weight.
-   You will use the pipette data along with hydrometer and sand fraction data to complete the particle size analysis for your sample. Nic has an electronic spreadsheet for this.

## References and Notes
